apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-petclinic-v08
  namespace: tbs
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - image: harbor.run.haas-222.pez.pivotal.io/tbs/spring-petclinic:v0.8
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
