apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: tbs
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - image: harbor.run.haas-222.pez.pivotal.io/tbs/spring-petclinic@sha256:c5d9e5b1cd56274bda241e2035c42c0d6fa0be367dc25cb2c004447697ad7e58
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
