apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic
  namespace: tbs
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: default
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: v1.2
      url: https://github.com/rammohanc/spring-petclinic.git
  successBuildHistoryLimit: 10
  tag: harbor.run.haas-222.pez.pivotal.io/tbs/spring-petclinic
